### ISSUE TITLE
Spoiler: new version coming soon

### ISSUE THREAD

**Issue by davidpagnon** [davidpagnon/Sports2D#10]
Thanks to @hunminkim98, you will soon get Sports2D to work:
- with pose estimation included in the package
- faster and more accurately than with OpenPose
- in real time
- with a more readable visual output
- and still in multi-person mode and advanced options if needed

(small changes to the visual will be made, but here is a spoiler anyway)

https://github.com/user-attachments/assets/59e5d9d1-2d12-44de-80e4-e94326a5f4df

**Comment by ntd1683** [comment]
Hello, when you run, do you need to adjust anything? I don't understand why when I run, the points on the people as well as the squares are not displayed, I leave all the default values, I use pose_135

**Comment by davidpagnon** [comment]
Hi @ntd1683!

Sorry for not answering earlier. I suppose the use of body_135 is the main issue. In any case, this version is now outdated. Could you completely remove your sports2d environment: conda env remove -n sports2d, reinstall it from the beginning, and tell me how it goes?

In any case, I have not tested any whole body model yet. Can you try to write `COCO_133` line 41 of Config_demo.toml? I haven't tested it but I should have written the code in such a way that it may work out of the box.

**Comment by davidpagnon** [comment]
More about the changes in the new version:

Rewrote the code after @hunminkim98's tests on (1) angle visualization, (2) with RTMPose, (3) including on webcam. 

Gave an impulse to implement many other changes:
- Used RTMPose rather than OpenPose or BlazePose (faster, more accurate, more flexible)
- Single process for both pose and angle estimation
- Webcam analysis available
- Body angle visualization
- Used entry points by default for clarity and simplicity
- Saved as OpenSim files: TRC for pose, MOT for angles
- Clearer documentation
- Better demo video
- Improved tracking IDs across frames
- Added some segment angles: Pelvis, Shoulders, Head
