### ISSUE TITLE
Error finding people from your demo video using the BLAZEPOSE method

### ISSUE THREAD

**Issue by ntd1683** [davidpagnon/Sports2D#13]
Error finding people from your demo video using the BLAZEPOSE method

I kept everything intact and followed your instructions, but the results came back with no person found and no csv file. Can you see if I did something wrong?

The steps I take : 

- step 1
`git clone https://github.com/davidpagnon/sports2d.git
cd sports2d
pip install .`

- step 2
`cd D:\project\sports2d\venv\lib\site-packages\Sports2D\demo`

- step 3
`ipython`
`from Sports2D import Sports2D
   ...: import os
   ...: Sports2D.detect_pose('Config_demo.toml')
   ...: Sports2D.compute_angles('Config_demo.toml')
`

### **Result**
`(venv) PS D:\project\sports2d\venv\lib\site-packages\Sports2D\demo> ipython
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from Sports2D import Sports2D
   ...: import os
   ...: Sports2D.detect_pose('Config_demo.toml')
   ...: Sports2D.compute_angles('Config_demo.toml')

---------------------------------------------------------------------
Detecting pose for video demo.mp4
---------------------------------------------------------------------
Downloading model to D:\Project\Sports2D\venv\lib\site-packages\mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite
Detecting 2D joint positions with BlazePose for D:\Project\Sports2D\venv\Lib\site-packages\Sports2D\Demo\demo.mp4.
Only one person can be detected by BlazePose. No interpolation nor filtering options available. Not plotting available.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Sorting people across frames.
No person detected or persons could not be associated across frames.
Pose detection took 11.46 s.

---------------------------------------------------------------------
Computing angles for video demo.mp4
for ['Right ankle', 'Left ankle', 'Right knee', 'Left knee', 'Right hip', 'Left hip', 'Right shoulder', 'Left shoulder', 'Right elbow', 'Left elbow']
and ['Right foot', 'Left foot', 'Right shank', 'Left shank', 'Right thigh', 'Left thigh', 'Trunk', 'Right arm', 'Left arm', 'Right forearm', 'Left forearm'].
---------------------------------------------------------------------
Retrieving csv position files in D:\Project\Sports2D\venv\Lib\site-packages\Sports2D\Demo...
0 persons found.
Saving video in D:\Project\Sports2D\venv\Lib\site-packages\Sports2D\Demo\demo.mp4.
Saving images in D:\Project\Sports2D\venv\Lib\site-packages\Sports2D\Demo\demo_img.
Joint and segment computation took 2.59 s.
`

**folder save :** 
![image](https://github.com/user-attachments/assets/3a955b38-9f1f-4187-a8c9-b5dc7ac4fbef)

**Comment by davidpagnon** [comment]
Hi, sorry for not answering earlier! 

I'm not sure what the problem is but this version is now outdated. I just released a new one that should be better in many ways.

Could you completely remove your sports2d environment: `conda env remove -n sports2d`, reinstall it from the beginning, and tell me how it goes?

**Comment by ntd1683** [comment]
Thank you very much, it works very well and is better than the old version
