### ISSUE TITLE
ERROR Colab

### ISSUE THREAD

**Issue by GUIARRUDA84** [davidpagnon/Sports2D#4]
Hello Guys, before I could run in Colab but now they are giving the following errors.

could you help me please?

update-alternatives: using /usr/bin/python3.10 to provide /usr/bin/python3 (python3) in auto mode Connecting to Google Drive... Mounted at /content/drive Installing Sports2D in Google Drive... Collecting Sports2D Downloading sports2d-0.2.5-py3-none-any.whl (2.6 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 10.8 MB/s eta 0:00:00 Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from Sports2D) (7.34.0) Requirement already satisfied: toml in /usr/local/lib/python3.10/dist-packages (from Sports2D) (0.10.2) Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from Sports2D) (1.23.5) Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.10/dist-packages (from Sports2D) (1.5.3) Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from Sports2D) (1.10.1) Collecting anytree (from Sports2D) Downloading anytree-2.9.0-py3-none-any.whl (38 kB) Requirement already satisfied: opencv-python in /usr/local/lib/python3.10/dist-packages (from Sports2D) (4.8.0.76) Collecting mediapipe (from Sports2D) Downloading mediapipe-0.10.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.5 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 39.3 MB/s eta 0:00:00 Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from Sports2D) (3.7.1) Collecting PyQt5 (from Sports2D) Downloading PyQt5-5.15.9-cp37-abi3-manylinux_2_17_x86_64.whl (8.4 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 82.6 MB/s eta 0:00:00 Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from Sports2D) (0.14.0) Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->Sports2D) (2.8.2) Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->Sports2D) (2023.3) Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from anytree->Sports2D) (1.16.0) Requirement already `satisfied`

**Comment by davidpagnon** [comment]
Hi there,

Yes I noticed that... It is due to the fact that Colab upgraded their Ubuntu version to 22.04, and OpenPose doesn't compile right anymore.
There is an ongoing conversation about it here:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1736#issuecomment-1652507856

Unfortunately, I won't have time to spend on it these days... If you have anyone who can help you in your team that is at ease with compilation, that may be solved relatively quickly! In that case I'm interested in your feedback so that I can implement the correction :)

**Comment by davidpagnon** [comment]
Hi @GUIARRUDA84 ,
(very) long story short, the colab version should be up now! Don't hesitate to tell me if you face any issues.
I'm closing this for now but if you experience any problem please reopen the issue.
