### ISSUE TITLE
Alphapose

### ISSUE THREAD

**Issue by st20042066** [davidpagnon/Sports2D#5]
Hello, just wondering when will the version of alphapose release? 
Sincerely asking, thank you.

**Comment by davidpagnon** [comment]
Hi, unfortunately I don't have much time to spend on this project currently... However, I have written a tool to convert AlphaPose output to OpenPose format, and then you can just use Sports2D normally.

https://github.com/perfanalytics/pose2sim/tree/main#with-alphapose

(by the way, Pose2Sim is more complex, but much more accurate, peer-reviewed, and works in 3D. If you can use several cameras, I would advise you to switch to this project. However, and despite I plan to solve it, it currently only tracks one person).

**Comment by st20042066** [comment]
That seems awesome, thank for you replying and advising, but my project is about monocular camera. Thanks a lot anyway!
