### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by 92Acp** [davidpagnon/Sports2D#8]
Hi! 

I'm getting the attached image error when I try to do the analysis in anaconda prompt
Can you help me?

![sports 2d error](https://github.com/davidpagnon/Sports2D/assets/135740101/84339f3a-383c-472b-a0d2-68616237701e)

**Comment by davidpagnon** [comment]
Hi, it's hard to tell without seeing the whole file, but it is telling you that there is a problem in your Config.toml file. What did you edit as compared to the original one?

**Comment by davidpagnon** [comment]
Oh, so running the Demonstration does not work? Have your tried the Colab version?

**Comment by 92Acp** [comment]
Yes! Even in the Colab version the same error occurs, even in the Demo version

**Comment by 92Acp** [comment]
the same error still persists

**Comment by davidpagnon** [comment]
Okay sorry, I'll have a look at it tonight, I need to go for now. I presume you are using the last version of Sports2D?

**Comment by 92Acp** [comment]
Okay thank you very much!
Yes, I'm using the latest version!

**Comment by 92Acp** [comment]
This is the Config_demo.toml file:


###############################################################################
## SPORTS2D PROJECT PARAMETERS                                               ##
###############################################################################

# Configure your project parameters here

# Then open an Anaconda prompt and enter:
# conda activate Sports2D
# ipython
# from Sports2D import Sports2D
# Sports2D.detect_pose('Config_demo.toml')
# Sports2D.compute_angles('Config_demo.toml')


[project]
video_dir = '' # BETWEEN SINGLE QUOTES! # If empty, result dir is current dir
video_files = ['your_video.mp4'] # video file (e.g.: 'demo.mp4') or list of video files (e.g.: ['demo.mp4', 'other.mov'])
result_dir = '' # BETWEEN SINGLE QUOTES! # If empty, project dir is current dir


[pose]
pose_algo = 'BLAZEPOSE' # 'OPENPOSE' or 'BLAZEPOSE' 
# OpenPose is more accurate and supports multi-person detection, but needs to be installed separately	
# Coming soon: 'deeplabcut', 'alphapose'
	
	[pose.BLAZEPOSE]
	# 0,1,2. 2 is slightly slower but more accurate
	model_complexity = 2 
		
	[pose.OPENPOSE]
	# Install OpenPose from https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md
	# BODY_25 is standard, BODY_25B is more accurate but requires downloading the model from 
	# https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/blob/master/experimental_models/README.md
	openpose_model = 'BODY_25' 
	
	# Installation path of openpose (between single quotes) 
	openpose_path = 'D:\softs\openpose-1.6.0-binaries-win64-gpu-flir-3d_recommended\openpose'
	

[compute_angles]
# Select joint angles among
# ['Right ankle', 'Left ankle', 'Right knee', 'Left knee', 'Right hip', 'Left hip', 'Right shoulder', 'Left shoulder', 'Right elbow', 'Left elbow', 'Right wrist', 'Left wrist']
joint_angles = ['Right ankle', 'Left ankle', 'Right knee', 'Left knee', 'Right hip', 'Left hip', 'Right shoulder', 'Left shoulder', 'Right elbow', 'Left elbow']

# Select segment angles among
# ['Right foot', 'Left foot', 'Right shank', 'Left shank', 'Right thigh', 'Left thigh', 'Trunk', 'Right arm', 'Left arm', 'Right forearm', 'Left forearm', 'Right hand', 'Left hand']
segment_angles = ['Right foot', 'Left foot', 'Right shank', 'Left shank', 'Right thigh', 'Left thigh', 'Trunk', 'Right arm', 'Left arm', 'Right forearm', 'Left forearm']

   	
	

# ADVANCED CONFIGURATION
	
[pose_advanced] # only for OPENPOSE
overwrite_pose = false # If false, don't run openpose again if json pose files are found. 
save_vid = true
save_img = true
interp_gap_smaller_than = 5 # do not interpolate bigger gaps
filter = true
show_plots = false
filter_type = 'butterworth' # butterworth, gaussian, LOESS, median
   [pose_advanced.butterworth]
   order = 4 
   cut_off_frequency = 6 # Hz
   [pose_advanced.gaussian]
   sigma_kernel = 1 #px
   [pose_advanced.loess]
   nb_values_used = 5 # = fraction of data used * nb frames
   [pose_advanced.median]
   kernel_size = 3


[compute_angles_advanced] # for OPENPOSE and BLAZEPOSE
show_angles_on_img = true
show_angles_on_vid = true
filter = false
show_plots = false
flip_left_right = true # Same angles whether the participant faces left/right. Set it to false if you want timeseries to be continuous even when the participent switches their stance.
filter_type = 'butterworth' # butterworth, gaussian, LOESS, median
   [compute_angles_advanced.butterworth]
   order = 4 
   cut_off_frequency = 6 # Hz
   [compute_angles_advanced.gaussian]
   sigma_kernel = 1 #px
   [compute_angles_advanced.loess]
   nb_values_used = 5 # = fraction of data used * nb frames
   [compute_angles_advanced.median]
   kernel_size = 3

**Comment by davidpagnon** [comment]
This is really strange, I cannot reproduce the problem, even with your Config file. It works for me locally, and the tests I run on Github (windows, linux, mac, with several python versions) don't report any issue.

Did you try to open your Config file with?

```python
import toml
toml.load(r'YOUR_CONFIG.TOML_PATH')
```

I seems like you may not be opening the right file. Do you have several Config_demo.toml files on your disk? 
From where do you run the script? Can you show me what's on the console before you type ipython?

**Comment by 92Acp** [comment]
Hi!! 
I use Anaconda Prompt to run the script

For this I use the sequence:

# conda activate Sports2D
# ipython
# from Sports2D import Sports2D
# Sports2D.detect_pose('Config_demo.toml')
# Sports2D.compute_angles('Config_demo.toml')

Send the image of what is before ipython
Thank you for your help!

![image](https://github.com/davidpagnon/Sports2D/assets/135740101/f2f38eed-e450-4256-94f2-3a18e11542f6)

**Comment by 92Acp** [comment]
I send here the image of the error that appears in the colab

![image](https://github.com/davidpagnon/Sports2D/assets/135740101/6741e765-ab15-4ef2-814e-2eb3b029462b)

**Comment by davidpagnon** [comment]
Okay, so you tried locally and on Colab.

- Locally, do you have a 'Config_demo.toml' and a 'your_video.mp4' files in `C:\User\Ana Carolina`? If you realize you did not edit the right files, two options: 
  - either do `cd <the_folder_of your_video_and_config>` and run again Sports2D
  - Or run `Sports2D.dectect_pose(r'<the_folder_of your_video_and_config>\Config_demo.toml')`
- In Colab, can you change `your_video.mp4` to `['your_video.mp4']`? I just tried again and it works. I will fix it in a little bit but I can't find time right now

**Comment by 92Acp** [comment]
I tried both options, in colab and locally, but the error remains the same

![image](https://github.com/davidpagnon/Sports2D/assets/135740101/61983a64-2910-45a8-bf69-592d8341a6d1)

![image](https://github.com/davidpagnon/Sports2D/assets/135740101/c2262d0e-3146-42db-ae77-d9ce766e94cc)

**Comment by davidpagnon** [comment]
It's really strange, it works flawlessly on my end, even after having completely uninstalled and reinstalled everything...
As for Colab, are you sure you have uploaded the video(s)? It tells you that the video is not found.
![image](https://github.com/davidpagnon/Sports2D/assets/54667644/c425467d-ac03-4a19-b341-170895c39e04)

**Comment by 92Acp** [comment]
Yes! I have uploaded the video

![image](https://github.com/davidpagnon/Sports2D/assets/135740101/ea230c11-8fe2-4e88-b582-8b92418178d6)

**Comment by 92Acp** [comment]
Here I uploaded another video, with a different name, it says the video is working
![image](https://github.com/davidpagnon/Sports2D/assets/135740101/0e45308f-98fd-4ce7-8488-c2a6e6afe73d)

However, in the run analysis I have this error, is the same as what appears in Anaconda Prompt
![image](https://github.com/davidpagnon/Sports2D/assets/135740101/42bb864e-2938-41ec-9100-9098af020ac5)

**Comment by davidpagnon** [comment]
Can you send me a link to your video and to your Config file maybe, so that I'm sure we are working with the same data?

**Comment by 92Acp** [comment]
Sure! 
This is the colab link
https://colab.research.google.com/github/davidpagnon/Sports2D/blob/main/Sports2D/Sports2D.ipynb#scrollTo=5dQqA5E6YeUS

And video link 
https://drive.google.com/drive/folders/11a52RIlDZZ9ZyKzVXABaZUp9wdZobHZf?usp=drive_link

**Comment by 92Acp** [comment]
Hey, I uninstalled and installed the entire package locally and now I was able to play the videos, I followed the entire process as I was doing previously!
Thank you for your help

**Comment by davidpagnon** [comment]
Oh okay 😅
I'm glad it works now!
